import { img5, img1, img3, img2, img4 } from "../assets/projectImg";

export const projectContent = [
  {
    id: 1,
    img: img5,
    title: "portfolio website",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia cumque alias illum libero a qui nobis adipisci, at, facilis eius,
      molestias vitae beatae explicabo accusamus quos`,
    githubLink: "https://github.com/yaya-usman",
    livesite: "localhost:3000",
    list: ["React", "CSS modules", "ContextAPI", "github pages"],
  },
  {
    id: 2,
    img: img1,
    title: "project2",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia cumque alias illum libero a qui nobis adipisci, at, facilis eius,
        molestias vitae beatae explicabo accusamus quos`,
    githubLink: "https://github.com/yaya-usman",
    livesite: "localhost:3000",
    list: ["React", "CSS modules", "Context API", "github pages"],
  },
  {
    id: 3,
    img: img3,
    title: "project3",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia cumque alias illum libero a qui nobis adipisci, at, facilis eius,
        molestias vitae beatae explicabo accusamus quos`,
    githubLink: "https://github.com/yaya-usman",
    livesite: "localhost:3000",
    list: ["React", "CSS modules", "Context API", "github pages"],
  },
  {
    id: 4,
    img: img2,
    title: "project4",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia cumque alias illum libero a qui nobis adipisci, at, facilis eius,
        molestias vitae beatae explicabo accusamus quos`,
    githubLink: "https://github.com/yaya-usman",
    livesite: "localhost:3000",
    list: ["React", "CSS modules", "Context API", "github pages"],
  },
  {
    id: 5,
    img: img4,
    title: "project5",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia cumque alias illum libero a qui nobis adipisci, at, facilis eius,
        molestias vitae beatae explicabo accusamus quos`,
    githubLink: "https://github.com/yaya-usman",
    livesite: "localhost:3000",
    list: ["React", "CSS modules", "Context API", "github pages"],
  },
];
